version: "3.5"
services:
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
